### ISSUE TITLE
Mention show

### ISSUE THREAD

**Issue by devlixz** [szweier/SZMentionsSwift#20]
how to add "@" become @steven on textView when selected list of mention steven? and also how to get text (String) on text View ? thanks anyway.

**Comment by szweier** [comment]
Hi sorry I'm a little confused by the second part of your question so I just wanted to clarify both.

1. When typing a mention and selecting from the list you would like the textview to show the @ symbol and the name instead of just the name correct?

2. What text is not showing on the textview for you?

**Comment by devlixz** [comment]
Thank you for reply

1. i will show with image

before
![screen shot 2016-10-10 at 9 47 28 am](https://cloud.githubusercontent.com/assets/22350941/19225949/d7eaf03e-8ece-11e6-89a5-aee56bb4a25c.png)


become
![screen shot 2016-10-10 at 9 48 04 am](https://cloud.githubusercontent.com/assets/22350941/19225952/e4018400-8ece-11e6-87b6-f0852579c8df.png)
*after select lists, name mentions add "@" in the begining


2. nope, i mean.. my question is, how to get the "text" on textview. 
i will explain using image on number 1.

example, there is button("Click Button") and label("This Label Here") 
if i tap the button, the label.text will become text from textview. thats all.. 
how to do that, i mean get the String text from textview SZMention and put it in to label.text

thankyou anyway

**Comment by szweier** [comment]
As for the first part of this issue there is some difficulty around keeping the @ symbols in the text that may make this feature take some time.  I'll see what I can do but I'm not sure this will make it into the library.   I will try though.

For the second question when you click the button the method that is called would need to do the following:

`self.label.text = self.textView.text`

This will take the text from the textView and apply it to your label.

**Comment by szweier** [comment]
@devlixz please try out this PR https://github.com/szweier/SZMentionsSwift/pull/23 

Using the code located at that URL you should be able to simply add an '@' to the list of mention names and have it work correctly.

As for the setting of the label the answer I placed above should solve that for you as well.

Please let me know.

**Comment by devlixz** [comment]
Hello sir,
thankyou very much 

where code, so i can add an '@' ?

**Comment by szweier** [comment]
All you would need to do is change the name you are passing into the mentions listener. 

If you look at the example I have in this repo you can open up SZExampleMentionstableViewDataManager.swift, you see on line 36 where I'm setting an array of names.  If I changed that to be "@Steven Zweier" instead of "Steven Zweier" it would show with the @ in the table that you choose from as well as show the @ inside of the textView after selecting that user.

**Comment by devlixz** [comment]
oh i see. Thankyou Verymuch sir ! your amazing!

**Comment by szweier** [comment]
No problem. Happy to help.

**Comment by nwios** [comment]
you can be adding "@" trigger to your UITextview at (ExampleMentionsTableViewDataManager.swift) class within (didSelectRowAt) delegate using the following code:

        var selectedMention = mentionsList[indexPath.row]
        selectedMention.name = "@" + selectedMention.name
        listener.addMention(selectedMention) 

instead of:

        listener.addMention(mentionsList[indexPath.row])



selectedMention property is CreateMention attribute finally, it`s work with me... Cheers.
