### ISSUE TITLE
How to cancel search?

### ISSUE THREAD

**Issue by camdengaba** [szweier/SZMentionsSwift#48]
Is there a way to cancel searching and not resign the textView's firstResponder? I want to allow users to cancel searching by tapping a button or the textView.

My mentions listener has spaceAfterMention, addMentionOnReturnKey, and searchSpaces all set to true.

**Comment by szweier** [comment]
@camdengaba you should be able to just call `hideMentionsList()`

**Comment by camdengaba** [comment]
That function is private. Though I suppose I could unlock the file and make it public

**Comment by szweier** [comment]
Sorry about that I may have answered too quickly. In order to do something like cancel searching you would likely need to be making adjustments to the code on your end and doing some type of editing to the text as well. My thought would be that you hide/remove the picker you display when `showMentionsListWithString(_ mentionString: String)` is called.  After that, because you have searchSpaces as true you would need to find the trigger, `@` by default, that started showing the picker and remove it from the text.  If you don't remove that `@` then showMentionsList will be called each character type after the trigger.  I hope that helps.

**Comment by szweier** [comment]
@camdengaba did you manage to resolve this issue?
